# Generated by Django 5.0.1 on 2026-05-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField(default=0)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kantin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kantin', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=200)),
                ('jam_buka', models.CharField(blank=True, max_length=50)),
                ('status_keramaian', models.CharField(choices=[('Sepi', 'Sepi'), ('Normal', 'Normal'), ('Ramai', 'Ramai')], default='Normal', max_length=10)),
                ('foto_warung', models.ImageField(blank=True, null=True, upload_to='warung_images/')),
                ('pemilik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warung', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kantin',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('deskripsi', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, help_text='Contoh: Halal, Pedas', max_length=50)),
                ('stok_tersedia', models.BooleanField(default=True)),
                ('jumlah_terjual', models.IntegerField(default=0)),
                ('kantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='budget.kantin')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pesan', models.TextField()),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('waktu_kirim', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('diproses', 'Diproses'), ('siap', 'Siap Diambil'), ('selesai', 'Selesai')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, help_text='Catatan untuk seluruh pesanan')),
                ('waktu_pesan', models.DateTimeField(auto_now_add=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_saya', to=settings.AUTH_USER_MODEL)),
                ('warung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.kantin')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=1)),
                ('harga_saat_pesan', models.IntegerField()),
                ('catatan_item', models.TextField(blank=True, help_text='Contoh: Gak pake seledri')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.pesanan')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('pemilik', 'Pemilik Warung'), ('admin', 'Admin Kampus')], default='mahasiswa', max_length=20)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bintang', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar', models.TextField()),
                ('waktu_review', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='budget.menu')),
            ],
        ),
    ]
