# Generated by Django 5.0.1 on 2026-05-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_notifikasi_options_kantin_deskripsi_and_more'),
        ('budget', '0002_update_models'),
    ]

    operations = [
    ]
