# Generated by Django 5.0.1 on 2026-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_merge_20260528_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='kantin',
            name='status_keramaian_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
